<?php
$no    = $_REQUEST['no'];
$in    = $_REQUEST['in'];
$out   = $_REQUEST['out'];
$denda = $_REQUEST['denda'];
$lama  = $_REQUEST['lama'];
$area  = $_REQUEST['area'];
$sewa  = $_REQUEST['sewa'];
$total = $_REQUEST['total'];
require('assets/fpdf/fpdf.php');

$pdf = new FPDF('P','mm',array(180,100));
$pdf->AddPage();
$pdf->SetFont('Arial','B',12);
$pdf->Cell(30,10,'X PLAZA SURABAYA');
$pdf->Ln();
$pdf->SetFont('Arial','',10);
$pdf->Cell(30,10,$no);
$pdf->Ln();
$pdf->Ln();
$pdf->Cell(30,10,'In     :');
$pdf->Cell(30,10,$in);
$pdf->Ln();
$pdf->Cell(30,10,'Out     :');
$pdf->Cell(30,10,$out);
$pdf->Ln();
$pdf->Cell(30,10,'Lama     :');
$pdf->Cell(30,10,$lama);
$pdf->Ln();
$pdf->Cell(30,10,'Area   :');
$pdf->Cell(30,10,$area);
$pdf->Ln();
$pdf->Cell(30,10,'Denda     :');
$pdf->Cell(30,10,$denda);
$pdf->Ln();
$pdf->Cell(30,10,'Sewa     :');
$pdf->Cell(30,10,$sewa);
$pdf->Ln();
$pdf->Cell(30,10,'______________________________________+');
$pdf->Ln();
$pdf->Cell(30,10,'Total     :');
$pdf->Cell(30,10,$total);
$pdf->Ln();
$pdf->Ln();
$pdf->SetFont('Arial','',10);
$pdf->Cell(30,10,'TERIMA KASIH');
$pdf->Ln();
$pdf->Cell(30,10,'ATAS KUNJUNGAN ANDA');
$pdf->Ln();
$pdf->Output();
?>
